apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegisml
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
commonLabels:
  app.kubernetes.io/name: aegisml
  app.kubernetes.io/component: inference
